ARCHS = arm64 arm64e

include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = MNACCModule
MNACCModule_BUNDLE_EXTENSION = bundle
MNACCModule_FILES = MNACCModule.m
MNACCModule_PRIVATE_FRAMEWORKS = ControlCenterUIKit
MNACCModule_INSTALL_PATH = /Library/ControlCenter/Bundles/

include $(THEOS_MAKE_PATH)/bundle.mk