ARCHS = arm64 arm64e

include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = messengernoadscc
messengernoadscc_BUNDLE_EXTENSION = bundle
messengernoadscc_FILES = messengernoadscc.m
messengernoadscc_PRIVATE_FRAMEWORKS = ControlCenterUIKit
messengernoadscc_INSTALL_PATH = /Library/ControlCenter/Bundles/

include $(THEOS_MAKE_PATH)/bundle.mk